// admin-vuetify/src/views/Profile.vue
<template>
<div>
    <h1>Profile</h1>
  <div v-if="profile">
    <div>
      <div>
        <img :src="profile.picture">
      </div>
      <div>
        <h2>{{ profile.name }}</h2>
        <p>{{ profile.email }}</p>
      </div>
    </div>

    <div>
      <pre>{{ JSON.stringify(profile, null, 2) }}</pre>
    </div>
  </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      profile: this.$auth.profile
    };
  },
  methods: {
    handleLoginEvent(data) {
      this.profile = data.profile;
    }
  }
};
</script>

// admin/src/views/Profile.jsx
import React from "react";
import { useAuth0 } from "../context/Auth0";

const Profile = () => {
    const { loading, currentUser } = useAuth0();

    if (loading || !currentUser) {
        return "Loading...";
    }

    return (
        <>
            <img src={currentUser.picture} alt="Profile" width="100" />

            <h2>{currentUser.name}</h2>
            <p>{currentUser.email}</p>
            <code>{JSON.stringify(currentUser, null, 2)}</code>
        </>
    );
};

export default Profile;
